function [vOutput] = BPF_05_3(vSignal, fs)

pf_05 = designfilt('bandpassiir','StopbandFrequency1',0.4,...
    'PassbandFrequency1',0.6,'PassbandFrequency2',3,...
    'StopbandFrequency2',4,'StopbandAttenuation1',60,...
    'PassbandRipple',1,'StopbandAttenuation2',40,...
    'SampleRate',fs,'DesignMethod','ellip');

vOutput=filtfilt(pf_05,vSignal);
