function [vOutput] = BPF_005_05(vSignal, fs)

% pf_05 = designfilt('bandpassiir','StopbandAttenuation',40,...
%         'CutoffFrequency1',0.05,'CutoffFrequency2',0.5, ...
%         'SampleRate',fs);
bp = designfilt('bandpassiir','StopbandFrequency1',0.03,...
    'PassbandFrequency1',0.05,'PassbandFrequency2',0.5,...
    'StopbandFrequency2',0.7,'StopbandAttenuation1',40,...
    'PassbandRipple',1,'StopbandAttenuation2',40,...
    'SampleRate',100,'DesignMethod','ellip');
vOutput=filter(bp,vSignal);
