function [hpf_005,lpf_05] = LPF_05(fs)

% designfilt('lowpassfir',...
%         'PassbandFrequency',0.5,'StopbandAttenuation',20, ...
%         'PassbandRipple',0.5,'SampleRate',fs);
lpf_05 = designfilt('lowpassfir','PassbandFrequency',0.4,...
    'StopbandFrequency',0.6,'PassbandRipple',2,...
    'StopbandAttenuation',20,'SampleRate',fs);
hpf_005 = designfilt('highpassfir','PassbandFrequency',0.06,...
    'StopbandFrequency',0.01,'PassbandRipple',2,...
    'StopbandAttenuation',20,'SampleRate',fs);

%'PassbandRipple',0.05,'FilterOrder',100,
%vOutput=filtfilt(pf_05,vSignal);
